name: Auto Merge Dependabot PRs

on:
  schedule:
    - cron: '0 6 * * *' 
  workflow_dispatch:     
  pull_request:
    types: [opened, labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest

    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Enable auto-merge for Dependabot PR
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash  # можно merge или rebase
