name: Scheduled Merge of Dependabot PRs

on:
  schedule:
    - cron: '0 6 * * *'  # каждый день в 06:00 UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Merge open Dependabot PRs
        uses: devops-infra/action-pull-request-merge@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          filter_author: dependabot[bot]
          method: squash  # можно заменить на merge или rebase
